# Site
name: "I Love Board Games"
title: "I Love Board Games"
description: "Board Game Reviews and More"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'G-JK05DQE30E'
disqus: 'i-love-board-games'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: pretty

# Authors
authors:
  joel:
    name: joel
    display_name: Joel Fischer
    gravatar: dcc6ade9135e7fab00f51ddf153a1e6e
    email: joeljfischer@gmail.com
    web: https://iloveboard.games
    follow: https://threads.net/iloveboard.games
    description: "Creator of \"I Love Board Games\" and \"Appealing Apps\" iOS Apps"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
